[package]
name = "vit"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.37", features = ["full"] }
warp = "0.3"
warp-embed = "0.5"
rust-embed = "8"
log = "0.4"
env_logger = "0.11"
