services:
  db:
    image: postgres:latest
    container_name: vit_db
    restart: unless-stopped
    volumes:
      - vit-db-pgdata-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vit_app
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: vit_db_admin
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=vitdev
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - vit-pgadmin-volume:/var/lib/pgadmin

volumes:
  vit-db-pgdata-volume:
    name: haast-db-postgres-data
  vit-pgadmin-volume:
    name: haast-pgadmin-volume-data
